# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: vumi-agents

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    environment:
        # Symfony environment variables
        APP_ENV: env
        SESSION_TABLE: !Ref SessionTable
        VERSION: 2
    iamRoleStatements:
        - Effect: Allow
          Resource: !GetAtt SessionTable.Arn
          Action: dynamodb:*Item

plugins:
  - ./vendor/bref/bref
  - serverless-lift
functions:
    # This function runs the Symfony website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'

        #vpc:
        #    securityGroupIds:
        #        - sg-002e56ba7dd7cc042
        #    subnetIds:
        #        - subnet-0c7dcdc7648510992
        #        - subnet-0ac0091161aa38c1e
        #        - subnet-0ba2a3b07a798fd3e
        #        - subnet-06199c8ca968e8d26
        #        - subnet-09d05b1e2656e342c
        #        - subnet-045415f5963648aab

    # This function let us run console commands in Lambda
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-81} # PHP
            - ${bref:layer.console} # The "console" layer

package:
    patterns:
        # Excluded files and folders for deployment
        - '!assets/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        - '!.idea/**'
        - '!.serverless/**'
        - '!docs/**'
        - '!docker/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
    individually: true

constructs:
    website:
        type: server-side-website
        assets:
            '/bundles/*': public/bundles
            '/build/*': public/build
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt
            # add here any file or directory that needs to be served from S3

resources:
    Resources:
        SessionTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: SessionTableVumi
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1